name: push-to-main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: docker build -t k9s-testing .
      
        # Build the Docker image
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/k6-testing:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/k6-testing:latest
      
