name: push-to-main

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker build
        run: docker build -t k9s-testing .
